### ISSUE TITLE
Can't build the theme

### ISSUE THREAD

**Issue by elgud** [markteekman/accessible-astro-starter#53]
I am trying to build this theme and I get the error:

Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
Require stack:
- /Users/elizabeth/Development/accessible-astro-starter/node_modules/sharp/lib/sharp.js
- /Users/elizabeth/Development/accessible-astro-starter/node_modules/sharp/lib/constructor.js
- /Users/elizabeth/Development/accessible-astro-starter/node_modules/sharp/lib/index.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/elizabeth/Development/accessible-astro-starter/node_modules/sharp/lib/sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/Users/elizabeth/Development/accessible-astro-starter/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)

Node.js v19.7.0

I am using the latest version of node.js.

When I do npm install, there are loads of vulnerabilities including 7 critical:

npm install

up to date, audited 1595 packages in 13s

306 packages are looking for funding
  run `npm fund` for details

49 vulnerabilities (3 low, 39 high, 7 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by elgud** [comment]
Fixed the issue by deleting the node-modules folder and running npm install again.

**Comment by markteekman** [comment]
Hey @elgud! Glad to see you've found a solution to this, it's the first thing I'd suggest when `npm install` isn't working 🤔 Weird though that 'sharp' package, it seems to have something to do with Apples M1 chip, oddly enough. Anyway, I'll close this issue since there's a fix 🙂
